export const ipcChannels = {
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  captureSelectScreen: 'capture:selectScreen',
  captureSetSelectedScreen: 'capture:setSelectedScreen',
  captureTakeScreenshot: 'capture:takeScreenshot',
  chatSendTurn: 'chat:sendTurn',
  audioTranscribe: 'audio:transcribe',
  transcribeGetToken: 'transcribe:getToken',
  ttsSpeak: 'tts:speak',
  recordingStart: 'recording:start',
  recordingStop: 'recording:stop',
  chatChunk: 'chat:chunk',
  chatDone: 'chat:done',
  chatError: 'chat:error',
  ttsAudio: 'tts:audio',
  ttsError: 'tts:error',
  agentSpawn: 'agent:spawn',
  agentSpawnError: 'agent:spawnError',
  agentClose: 'agent:close',
  agentGetContext: 'agent:getContext',
  agentCommandFlash: 'agent:commandFlash',
  agentUpdate: 'agent:update',
  agentFollowUp: 'agent:followUp',
  agentRunAction: 'agent:runAction',
  windowGetContext: 'window:getContext',
  executeShell: 'shell:execute'
} as const;
